const Songs =
[
  {
    ID: "0",
    UUID: "33898e77-53b5-408d-8cb5-265f6a083d0e",
    RawFileName: "A Sky Full of Stars - Coldplay",
    SongName: "A Sky Full of Stars",
    Artist: "Coldplay",
    SongUri: require("../assets/music/ASkyFullofStars-Coldplay.mp3"),
    SongAlbumImg: require("../assets/music/ASkyFullofStars-Coldplay.jpg"),
    SongLyric: "assets/music/ASkyFullofStars-Coldplay.lrc",
    FileSize: "10.22 MB"
  },
  {
    ID: "1",
    UUID: "6abeaa06-342b-4aad-ad95-bd2a78bad9ff",
    RawFileName: "After All - Elton John,Charlie Puth",
    SongName: "After All",
    Artist: "Elton John,Charlie Puth",
    SongUri: require("../assets/music/AfterAll-EltonJohnANDCharliePuth.mp3"),
    SongAlbumImg: require("../assets/music/AfterAll-EltonJohnANDCharliePuth.jpg"),
    SongLyric: "assets/music/AfterAll-EltonJohnANDCharliePuth.lrc",
    FileSize: "3.19 MB"
  },
  {
    ID: "2",
    UUID: "fc95e5b9-91a1-4185-afe9-8c0a80705620",
    RawFileName: "Attention - Charlie Puth",
    SongName: "Attention",
    Artist: "Charlie Puth",
    SongUri: require("../assets/music/Attention-CharliePuth.mp3"),
    SongAlbumImg: require("../assets/music/Attention-CharliePuth.jpg"),
    SongLyric: "assets/music/Attention-CharliePuth.lrc",
    FileSize: "8.07 MB"
  },
  {
    ID: "3",
    UUID: "2993866d-865b-4399-980c-bd73fb8a94aa",
    RawFileName: "Beautiful Mistakes - Maroon 5,Megan Thee Stallion",
    SongName: "Beautiful Mistakes",
    Artist: "Maroon 5,Megan Thee Stallion",
    SongUri: require("../assets/music/BeautifulMistakes-Maroon5ANDMeganTheeStallion.mp3"),
    SongAlbumImg: require("../assets/music/BeautifulMistakes-Maroon5ANDMeganTheeStallion.jpg"),
    SongLyric: "assets/music/BeautifulMistakes-Maroon5ANDMeganTheeStallion.lrc",
    FileSize: "8.68 MB"
  },
  {
    ID: "4",
    UUID: "7bb35c67-b5b3-4802-8e87-ac3959767f37",
    RawFileName: "Bring Me Back (feat. Claire Ridgely) - Miles Away",
    SongName: "Bring Me Back (feat. Claire Ridgely)",
    Artist: "Miles Away",
    SongUri: require("../assets/music/BringMeBack(feat.ClaireRidgely)-MilesAway.mp3"),
    SongAlbumImg: require("../assets/music/BringMeBack(feat.ClaireRidgely)-MilesAway.jpg"),
    SongLyric: "assets/music/BringMeBack(feat.ClaireRidgely)-MilesAway.lrc",
    FileSize: "3.34 MB"
  },
  {
    ID: "5",
    UUID: "479b8bf0-ab64-4320-a789-b9547619d004",
    RawFileName: "Can We Kiss Forever-Kina,Adriana Proenza",
    SongName: "Can We Kiss Forever",
    Artist: "Kina,Adriana Proenza",
    SongUri: require("../assets/music/CanWeKissForever-KinaANDAdrianaProenza.mp3"),
    SongAlbumImg: require("../assets/music/CanWeKissForever-KinaANDAdrianaProenza.jpg"),
    SongLyric: "assets/music/CanWeKissForever-KinaANDAdrianaProenza.lrc",
    FileSize: "7.17 MB"
  },
  {
    ID: "6",
    UUID: "ebafbfc1-3d1f-424b-95c9-880dd4c6c4ff",
    RawFileName: "Ceasefire - BEAUZ,Luke Anders,Ducka Shan,Becca Krueger,Eliason",
    SongName: "Ceasefire",
    Artist: "BEAUZ,Luke Anders,Ducka Shan,Becca Krueger,Eliason",
    SongUri: require("../assets/music/Ceasefire-BEAUZANDLukeAndersANDDuckaShanANDBeccaKruegerANDEl.mp3"),
    SongAlbumImg: require("../assets/music/Ceasefire-BEAUZANDLukeAndersANDDuckaShanANDBeccaKruegerANDEl.jpg"),
    SongLyric: "assets/music/Ceasefire-BEAUZANDLukeAndersANDDuckaShanANDBeccaKruegerANDEl.lrc",
    FileSize: "7.56 MB"
  },
  {
    ID: "7",
    UUID: "09b0189d-d345-4d93-9d9f-fbecdb7f34d7",
    RawFileName: "Clsr (Aash Mehta Flip) - The Chainsmokers,Aash Mehta,Halsey",
    SongName: "Clsr (Aash Mehta Flip)",
    Artist: "The Chainsmokers,Aash Mehta,Halsey",
    SongUri: require("../assets/music/Clsr(AashMehtaFlip)-TheChainsmokersANDAashMehtaANDHalsey.mp3"),
    SongAlbumImg: require("../assets/music/Clsr(AashMehtaFlip)-TheChainsmokersANDAashMehtaANDHalsey.jpg"),
    SongLyric: "assets/music/Clsr(AashMehtaFlip)-TheChainsmokersANDAashMehtaANDHalsey.lrc",
    FileSize: "10.74 MB"
  },
  {
    ID: "8",
    UUID: "ff86a117-65dc-48ae-b15e-8fe2737b8129",
    RawFileName: "Dangerously - Charlie Puth",
    SongName: "Dangerously",
    Artist: "Charlie Puth",
    SongUri: require("../assets/music/Dangerously-CharliePuth.mp3"),
    SongAlbumImg: require("../assets/music/Dangerously-CharliePuth.jpg"),
    SongLyric: "assets/music/Dangerously-CharliePuth.lrc",
    FileSize: "4.56 MB"
  },
  {
    ID: "9",
    UUID: "53440aaa-2c43-4cb2-b31d-e32a09fa0bc1",
    RawFileName: "Daylight - Maroon 5",
    SongName: "Daylight",
    Artist: "Maroon 5",
    SongUri: require("../assets/music/Daylight-Maroon5.mp3"),
    SongAlbumImg: require("../assets/music/Daylight-Maroon5.jpg"),
    SongLyric: "assets/music/Daylight-Maroon5.lrc",
    FileSize: "3.46 MB"
  },
  {
    ID: "10",
    UUID: "55220661-3da6-485d-833b-90c5ba34a190",
    RawFileName: "Deep End - William Black",
    SongName: "Deep End",
    Artist: "William Black",
    SongUri: require("../assets/music/DeepEnd-WilliamBlack.mp3"),
    SongAlbumImg: require("../assets/music/DeepEnd-WilliamBlack.jpg"),
    SongLyric: "assets/music/DeepEnd-WilliamBlack.lrc",
    FileSize: "7.95 MB"
  },
  {
    ID: "11",
    UUID: "553e73bb-c8bf-4a66-b355-ba748a95d5a6",
    RawFileName: "Disenchanted - My Chemical Romance",
    SongName: "Disenchanted",
    Artist: "My Chemical Romance",
    SongUri: require("../assets/music/Disenchanted-MyChemicalRomance.mp3"),
    SongAlbumImg: require("../assets/music/Disenchanted-MyChemicalRomance.jpg"),
    SongLyric: "assets/music/Disenchanted-MyChemicalRomance.lrc",
    FileSize: "11.26 MB"
  },
  {
    ID: "12",
    UUID: "f4da671c-8bad-4b2e-9794-026c5d580dcf",
    RawFileName: "Don't Say (Felix Palmqvist & Severo Remix) - The Chainsmokers,Emily Warren,Felix Palmqvist,Severo",
    SongName: "Don't Say (Felix Palmqvist & Severo Remix)",
    Artist: "The Chainsmokers,Emily Warren,Felix Palmqvist,Severo",
    SongUri: require("../assets/music/Don'tSay(FelixPalmqvistANDSeveroRemix)-TheChainsmokersANDEmi.mp3"),
    SongAlbumImg: require("../assets/music/Don'tSay(FelixPalmqvistANDSeveroRemix)-TheChainsmokersANDEmi.jpg"),
    SongLyric: "assets/music/Don'tSay(FelixPalmqvistANDSeveroRemix)-TheChainsmokersANDEmi.lrc",
    FileSize: "7.69 MB"
  },
  {
    ID: "13",
    UUID: "ed8712ba-eee3-42f6-a065-0655d6ed6f24",
    RawFileName: "Empty Cups - Charlie Puth",
    SongName: "Empty Cups",
    Artist: "Charlie Puth",
    SongUri: require("../assets/music/EmptyCups-CharliePuth.mp3"),
    SongAlbumImg: require("../assets/music/EmptyCups-CharliePuth.jpg"),
    SongLyric: "assets/music/EmptyCups-CharliePuth.lrc",
    FileSize: "6.52 MB"
  },
  {
    ID: "14",
    UUID: "a5869a00-308a-4fff-8d26-322f2db8e359",
    RawFileName: "Everglow - Coldplay",
    SongName: "Everglow",
    Artist: "Coldplay",
    SongUri: require("../assets/music/Everglow-Coldplay.mp3"),
    SongAlbumImg: require("../assets/music/Everglow-Coldplay.jpg"),
    SongLyric: "assets/music/Everglow-Coldplay.lrc",
    FileSize: "4.32 MB"
  },
  {
    ID: "15",
    UUID: "fef48336-c325-471b-a21d-457738693d52",
    RawFileName: "Fix You - Coldplay",
    SongName: "Fix You",
    Artist: "Coldplay",
    SongUri: require("../assets/music/FixYou-Coldplay.mp3"),
    SongAlbumImg: require("../assets/music/FixYou-Coldplay.jpg"),
    SongLyric: "assets/music/FixYou-Coldplay.lrc",
    FileSize: "11.28 MB"
  },
  {
    ID: "16",
    UUID: "475a59b2-5511-4be5-971e-cbd663596ee2",
    RawFileName: "Free(From Disneys The One And Only Ivan) - Charlie Puth",
    SongName: "Free(From Disneys The One And Only Ivan)",
    Artist: "Charlie Puth",
    SongUri: require("../assets/music/Free(FromDisneysTheOneAndOnlyIvan)-CharliePuth.mp3"),
    SongAlbumImg: null,
    SongLyric: null,
    FileSize: "8.74 MB"
  },
  {
    ID: "17",
    UUID: "4ebdbf66-a8af-4f2e-8ac5-aafaa2bf42c7",
    RawFileName: "Gamle Dager - Morgan Sulele",
    SongName: "Gamle Dager",
    Artist: "Morgan Sulele",
    SongUri: require("../assets/music/GamleDager-MorganSulele.mp3"),
    SongAlbumImg: null,
    SongLyric: null,
    FileSize: "2.83 MB"
  },
  {
    ID: "18",
    UUID: "4f5caa1c-0a8b-4a0d-a615-52cc08229d7b",
    RawFileName: "Girls Like You - Maroon 5,Cardi B",
    SongName: "Girls Like You",
    Artist: "Maroon 5,Cardi B",
    SongUri: require("../assets/music/GirlsLikeYou-Maroon5ANDCardiB.mp3"),
    SongAlbumImg: require("../assets/music/GirlsLikeYou-Maroon5ANDCardiB.jpg"),
    SongLyric: "assets/music/GirlsLikeYou-Maroon5ANDCardiB.lrc",
    FileSize: "5.39 MB"
  },
  {
    ID: "19",
    UUID: "06e9b7a2-b6f7-4961-bb26-23fbb5238bd2",
    RawFileName: "Gotta Be You - One Direction",
    SongName: "Gotta Be You",
    Artist: "One Direction",
    SongUri: require("../assets/music/GottaBeYou-OneDirection.mp3"),
    SongAlbumImg: require("../assets/music/GottaBeYou-OneDirection.jpg"),
    SongLyric: "assets/music/GottaBeYou-OneDirection.lrc",
    FileSize: "9.34 MB"
  },
  {
    ID: "20",
    UUID: "63399dbd-5a30-4805-b147-d0518ef65b8e",
    RawFileName: "History - One Direction",
    SongName: "History",
    Artist: "One Direction",
    SongUri: require("../assets/music/History-OneDirection.mp3"),
    SongAlbumImg: require("../assets/music/History-OneDirection.jpg"),
    SongLyric: "assets/music/History-OneDirection.lrc",
    FileSize: "7.15 MB"
  },
  {
    ID: "21",
    UUID: "4dbcadc8-27fe-4cf8-bbd9-b8a32fd11959",
    RawFileName: "How Long - Charlie Puth",
    SongName: "How Long",
    Artist: "Charlie Puth",
    SongUri: require("../assets/music/HowLong-CharliePuth.mp3"),
    SongAlbumImg: require("../assets/music/HowLong-CharliePuth.jpg"),
    SongLyric: "assets/music/HowLong-CharliePuth.lrc",
    FileSize: "3.03 MB"
  },
  {
    ID: "22",
    UUID: "4ff1740d-8f94-4b1a-b990-9a98c64b2623",
    RawFileName: "I Don’t Think That I Like Her - Charlie Puth",
    SongName: "I Don’t Think That I Like Her",
    Artist: "Charlie Puth",
    SongUri: require("../assets/music/IDon’tThinkThatILikeHer-CharliePuth.mp3"),
    SongAlbumImg: require("../assets/music/IDon’tThinkThatILikeHer-CharliePuth.jpg"),
    SongLyric: "assets/music/IDon’tThinkThatILikeHer-CharliePuth.lrc",
    FileSize: "7.19 MB"
  },
  {
    ID: "23",
    UUID: "7d8443c6-5b3d-4552-8aba-bcf6f0bf461e",
    RawFileName: "If You Leave Me Now - Boyz II Men,Charlie Puth",
    SongName: "If You Leave Me Now",
    Artist: "Boyz II Men,Charlie Puth",
    SongUri: require("../assets/music/IfYouLeaveMeNow-BoyzIIMenANDCharliePuth.mp3"),
    SongAlbumImg: require("../assets/music/IfYouLeaveMeNow-BoyzIIMenANDCharliePuth.jpg"),
    SongLyric: "assets/music/IfYouLeaveMeNow-BoyzIIMenANDCharliePuth.lrc",
    FileSize: "9.24 MB"
  },
  {
    ID: "24",
    UUID: "236daff3-ebd1-4efa-93b0-03c8451a0df8",
    RawFileName: "Is It Just Me (feat. Charlie Puth) - Sasha Alex Sloan",
    SongName: "Is It Just Me (feat. Charlie Puth)",
    Artist: "Sasha Alex Sloan",
    SongUri: require("../assets/music/IsItJustMe(feat.CharliePuth)-SashaAlexSloan.mp3"),
    SongAlbumImg: require("../assets/music/IsItJustMe(feat.CharliePuth)-SashaAlexSloan.jpg"),
    SongLyric: "assets/music/IsItJustMe(feat.CharliePuth)-SashaAlexSloan.lrc",
    FileSize: "5.89 MB"
  },
  {
    ID: "25",
    UUID: "7464c948-076a-481f-b36b-b25b5bc61b73",
    RawFileName: "Jealous - Faustix",
    SongName: "Jealous",
    Artist: "Faustix",
    SongUri: require("../assets/music/Jealous-Faustix.mp3"),
    SongAlbumImg: require("../assets/music/Jealous-Faustix.jpg"),
    SongLyric: "assets/music/Jealous-Faustix.lrc",
    FileSize: "8.53 MB"
  },
  {
    ID: "26",
    UUID: "51f3c66c-a1e6-43f2-bb62-3ac806ebbb3d",
    RawFileName: "Just A Feeling - Maroon 5",
    SongName: "Just A Feeling",
    Artist: "Maroon 5",
    SongUri: require("../assets/music/JustAFeeling-Maroon5.mp3"),
    SongAlbumImg: require("../assets/music/JustAFeeling-Maroon5.jpg"),
    SongLyric: "assets/music/JustAFeeling-Maroon5.lrc",
    FileSize: "8.64 MB"
  },
  {
    ID: "27",
    UUID: "17a26845-0997-44af-acf3-959d32d8a19f",
    RawFileName: "Keep You Mine - NOTD,SHY Martin",
    SongName: "Keep You Mine",
    Artist: "NOTD,SHY Martin",
    SongUri: require("../assets/music/KeepYouMine-NOTDANDSHYMartin.mp3"),
    SongAlbumImg: require("../assets/music/KeepYouMine-NOTDANDSHYMartin.jpg"),
    SongLyric: "assets/music/KeepYouMine-NOTDANDSHYMartin.lrc",
    FileSize: "6.67 MB"
  },
  {
    ID: "28",
    UUID: "797fb807-ba5f-464e-8556-00f4bc4d72e0",
    RawFileName: "Left and Right (Feat. Jung Kook of BTS) - Charlie Puth,BTS (防弹少年团)",
    SongName: "Left and Right (Feat. Jung Kook of BTS)",
    Artist: "Charlie Puth,BTS (防弹少年团)",
    SongUri: require("../assets/music/LeftandRight(Feat.JungKookofBTS)-CharliePuthANDBTS(防弹少年团).mp3"),
    SongAlbumImg: require("../assets/music/LeftandRight(Feat.JungKookofBTS)-CharliePuthANDBTS(防弹少年团).jpg"),
    SongLyric: "assets/music/LeftandRight(Feat.JungKookofBTS)-CharliePuthANDBTS(防弹少年团).lrc",
    FileSize: "5.9 MB"
  },
  {
    ID: "29",
    UUID: "399ad5e6-a13f-48e6-933d-00e2ba34b249",
    RawFileName: "Let Somebody Go - Coldplay,Selena Gomez",
    SongName: "Let Somebody Go",
    Artist: "Coldplay,Selena Gomez",
    SongUri: require("../assets/music/LetSomebodyGo-ColdplayANDSelenaGomez.mp3"),
    SongAlbumImg: require("../assets/music/LetSomebodyGo-ColdplayANDSelenaGomez.jpg"),
    SongLyric: "assets/music/LetSomebodyGo-ColdplayANDSelenaGomez.lrc",
    FileSize: "3.69 MB"
  },
  {
    ID: "30",
    UUID: "b203f249-c173-42e3-926f-9a25ef77ee3e",
    RawFileName: "Like 1999 - Valley",
    SongName: "Like 1999",
    Artist: "Valley",
    SongUri: require("../assets/music/Like1999-Valley.mp3"),
    SongAlbumImg: require("../assets/music/Like1999-Valley.jpg"),
    SongLyric: "assets/music/Like1999-Valley.lrc",
    FileSize: "5.52 MB"
  },
  {
    ID: "31",
    UUID: "a384b474-e268-4ce4-ab6f-4a60e0b9bb0b",
    RawFileName: "Love You Like the Movies - Anthem Lights",
    SongName: "Love You Like the Movies",
    Artist: "Anthem Lights",
    SongUri: require("../assets/music/LoveYouLiketheMovies-AnthemLights.mp3"),
    SongAlbumImg: require("../assets/music/LoveYouLiketheMovies-AnthemLights.jpg"),
    SongLyric: "assets/music/LoveYouLiketheMovies-AnthemLights.lrc",
    FileSize: "3.48 MB"
  },
  {
    ID: "32",
    UUID: "13dcda52-2c1b-490f-91a0-e007dc2d0e85",
    RawFileName: "Maps - Maroon 5",
    SongName: "Maps",
    Artist: "Maroon 5",
    SongUri: require("../assets/music/Maps-Maroon5.mp3"),
    SongAlbumImg: require("../assets/music/Maps-Maroon5.jpg"),
    SongLyric: "assets/music/Maps-Maroon5.lrc",
    FileSize: "7.25 MB"
  },
  {
    ID: "33",
    UUID: "449ce89f-6157-45f4-8458-9277c4c0209f",
    RawFileName: "Memories - Maroon 5",
    SongName: "Memories",
    Artist: "Maroon 5",
    SongUri: require("../assets/music/Memories-Maroon5.mp3"),
    SongAlbumImg: require("../assets/music/Memories-Maroon5.jpg"),
    SongLyric: "assets/music/Memories-Maroon5.lrc",
    FileSize: "7.23 MB"
  },
  {
    ID: "34",
    UUID: "8c2b3dcb-fdb8-456e-bb75-2beccf973fc6",
    RawFileName: "Miracles - Coldplay",
    SongName: "Miracles",
    Artist: "Coldplay",
    SongUri: require("../assets/music/Miracles-Coldplay.mp3"),
    SongAlbumImg: require("../assets/music/Miracles-Coldplay.jpg"),
    SongLyric: "assets/music/Miracles-Coldplay.lrc",
    FileSize: "8.98 MB"
  },
  {
    ID: "35",
    UUID: "88749208-57b1-47aa-a26b-67f1dd383b16",
    RawFileName: "Night Changes - One Direction",
    SongName: "Night Changes",
    Artist: "One Direction",
    SongUri: require("../assets/music/NightChanges-OneDirection.mp3"),
    SongAlbumImg: require("../assets/music/NightChanges-OneDirection.jpg"),
    SongLyric: "assets/music/NightChanges-OneDirection.lrc",
    FileSize: "5.18 MB"
  },
  {
    ID: "36",
    UUID: "e00d3d72-f96e-4a33-8e6d-b04e848de338",
    RawFileName: "No More Drama - Charlie Puth",
    SongName: "No More Drama",
    Artist: "Charlie Puth",
    SongUri: require("../assets/music/NoMoreDrama-CharliePuth.mp3"),
    SongAlbumImg: require("../assets/music/NoMoreDrama-CharliePuth.jpg"),
    SongLyric: "assets/music/NoMoreDrama-CharliePuth.lrc",
    FileSize: "5.34 MB"
  },
  {
    ID: "37",
    UUID: "6339b7f5-a823-4509-a895-e91cd812f6b3",
    RawFileName: "Nobody Compares - One Direction",
    SongName: "Nobody Compares",
    Artist: "One Direction",
    SongUri: require("../assets/music/NobodyCompares-OneDirection.mp3"),
    SongAlbumImg: require("../assets/music/NobodyCompares-OneDirection.jpg"),
    SongLyric: "assets/music/NobodyCompares-OneDirection.lrc",
    FileSize: "3.23 MB"
  },
  {
    ID: "38",
    UUID: "e40dfbe4-d241-4ee3-b2d5-4300432fe2fa",
    RawFileName: "One Thing - One Direction",
    SongName: "One Thing",
    Artist: "One Direction",
    SongUri: require("../assets/music/OneThing-OneDirection.mp3"),
    SongAlbumImg: require("../assets/music/OneThing-OneDirection.jpg"),
    SongLyric: "assets/music/OneThing-OneDirection.lrc",
    FileSize: "3.01 MB"
  },
  {
    ID: "39",
    UUID: "3d8389ef-6f12-422e-b9b1-567bc73dbf68",
    RawFileName: "Oops - Charlie Puth,Little Mix",
    SongName: "Oops",
    Artist: "Charlie Puth,Little Mix",
    SongUri: require("../assets/music/Oops-CharliePuthANDLittleMix.mp3"),
    SongAlbumImg: null,
    SongLyric: null,
    FileSize: "7.81 MB"
  },
  {
    ID: "40",
    UUID: "5a995e13-6253-45ad-b1d7-10240ee1dd59",
    RawFileName: "Overtime - Cash Cash",
    SongName: "Overtime",
    Artist: "Cash Cash",
    SongUri: require("../assets/music/Overtime-CashCash.mp3"),
    SongAlbumImg: require("../assets/music/Overtime-CashCash.jpg"),
    SongLyric: "assets/music/Overtime-CashCash.lrc",
    FileSize: "3.76 MB"
  },
  {
    ID: "41",
    UUID: "3ccc9b04-184d-4a3e-b51b-35b684e129c7",
    RawFileName: "Paradise - Coldplay",
    SongName: "Paradise",
    Artist: "Coldplay",
    SongUri: require("../assets/music/Paradise-Coldplay.mp3"),
    SongAlbumImg: require("../assets/music/Paradise-Coldplay.jpg"),
    SongLyric: "assets/music/Paradise-Coldplay.lrc",
    FileSize: "10.63 MB"
  },
  {
    ID: "42",
    UUID: "6ebb4e21-4734-4035-9b2c-49e1a3d618fd",
    RawFileName: "Patient - Charlie Puth",
    SongName: "Patient",
    Artist: "Charlie Puth",
    SongUri: require("../assets/music/Patient-CharliePuth.mp3"),
    SongAlbumImg: require("../assets/music/Patient-CharliePuth.jpg"),
    SongLyric: "assets/music/Patient-CharliePuth.lrc",
    FileSize: "7.27 MB"
  },
  {
    ID: "43",
    UUID: "b92f928d-d1fd-4d83-b434-7524a3071e86",
    RawFileName: "Say Something - A Great Big World",
    SongName: "Say Something",
    Artist: "A Great Big World",
    SongUri: require("../assets/music/SaySomething-AGreatBigWorld.mp3"),
    SongAlbumImg: require("../assets/music/SaySomething-AGreatBigWorld.jpg"),
    SongLyric: "assets/music/SaySomething-AGreatBigWorld.lrc",
    FileSize: "8.8 MB"
  },
  {
    ID: "44",
    UUID: "dfb571f0-e508-4a62-ba93-1f6737438eb6",
    RawFileName: "See You Again - Wiz Khalifa,Charlie Puth",
    SongName: "See You Again",
    Artist: "Wiz Khalifa,Charlie Puth",
    SongUri: require("../assets/music/SeeYouAgain-WizKhalifaANDCharliePuth.mp3"),
    SongAlbumImg: require("../assets/music/SeeYouAgain-WizKhalifaANDCharliePuth.jpg"),
    SongLyric: "assets/music/SeeYouAgain-WizKhalifaANDCharliePuth.lrc",
    FileSize: "8.76 MB"
  },
  {
    ID: "45",
    UUID: "e036c429-27f0-4bfd-ab57-7288bcf9a694",
    RawFileName: "Slow It Down - Charlie Puth",
    SongName: "Slow It Down",
    Artist: "Charlie Puth",
    SongUri: require("../assets/music/SlowItDown-CharliePuth.mp3"),
    SongAlbumImg: require("../assets/music/SlowItDown-CharliePuth.jpg"),
    SongLyric: "assets/music/SlowItDown-CharliePuth.lrc",
    FileSize: "2.91 MB"
  },
  {
    ID: "46",
    UUID: "a1c4e01b-5f47-4e62-a991-d580d1c02a2d",
    RawFileName: "Something Just Like This - The Chainsmokers,Coldplay",
    SongName: "Something Just Like This",
    Artist: "The Chainsmokers,Coldplay",
    SongUri: require("../assets/music/SomethingJustLikeThis-TheChainsmokersANDColdplay.mp3"),
    SongAlbumImg: require("../assets/music/SomethingJustLikeThis-TheChainsmokersANDColdplay.jpg"),
    SongLyric: "assets/music/SomethingJustLikeThis-TheChainsmokersANDColdplay.lrc",
    FileSize: "9.45 MB"
  },
  {
    ID: "47",
    UUID: "eebb358a-0280-4a99-93be-1e78532fbb74",
    RawFileName: "Sugar - Maroon 5",
    SongName: "Sugar",
    Artist: "Maroon 5",
    SongUri: require("../assets/music/Sugar-Maroon5.mp3"),
    SongAlbumImg: require("../assets/music/Sugar-Maroon5.jpg"),
    SongLyric: "assets/music/Sugar-Maroon5.lrc",
    FileSize: "8.99 MB"
  },
  {
    ID: "48",
    UUID: "9529da71-f98d-4137-9249-d2c3fe596939",
    RawFileName: "Summer Feelings(电影《史努比狗》插曲)-Charlie Puth,Lennon Stella",
    SongName: "Summer Feelings(电影《史努比狗》插曲)",
    Artist: "Charlie Puth,Lennon Stella",
    SongUri: require("../assets/music/SummerFeelings(电影《史努比狗》插曲)-CharliePuthANDLennonStella.mp3"),
    SongAlbumImg: require("../assets/music/SummerFeelings(电影《史努比狗》插曲)-CharliePuthANDLennonStella.jpg"),
    SongLyric: null,
    FileSize: "2.45 MB"
  },
  {
    ID: "49",
    UUID: "942859cf-0c32-4064-a2c8-d46f423d760c",
    RawFileName: "Sunroof - Nicky Youre,Dazy",
    SongName: "Sunroof",
    Artist: "Nicky Youre,Dazy",
    SongUri: require("../assets/music/Sunroof-NickyYoureANDDazy.mp3"),
    SongAlbumImg: require("../assets/music/Sunroof-NickyYoureANDDazy.jpg"),
    SongLyric: "assets/music/Sunroof-NickyYoureANDDazy.lrc",
    FileSize: "6.22 MB"
  },
  {
    ID: "50",
    UUID: "74af385e-1528-42e4-b0c3-66a50aff529b",
    RawFileName: "THATS WHAT I WANT - Lil Nas X",
    SongName: "THATS WHAT I WANT",
    Artist: "Lil Nas X",
    SongUri: require("../assets/music/THATSWHATIWANT-LilNasX.mp3"),
    SongAlbumImg: require("../assets/music/THATSWHATIWANT-LilNasX.jpg"),
    SongLyric: "assets/music/THATSWHATIWANT-LilNasX.lrc",
    FileSize: "5.49 MB"
  },
  {
    ID: "51",
    UUID: "d226c26f-e39f-4ec9-b111-2008071fea9f",
    RawFileName: "The Scientist - Coldplay",
    SongName: "The Scientist",
    Artist: "Coldplay",
    SongUri: require("../assets/music/TheScientist-Coldplay.mp3"),
    SongAlbumImg: require("../assets/music/TheScientist-Coldplay.jpg"),
    SongLyric: "assets/music/TheScientist-Coldplay.lrc",
    FileSize: "4.75 MB"
  },
  {
    ID: "52",
    UUID: "5ae47771-6eb9-453d-a789-46e198cd1cd5",
    RawFileName: "The Way I Am - Charlie Puth",
    SongName: "The Way I Am",
    Artist: "Charlie Puth",
    SongUri: require("../assets/music/TheWayIAm-CharliePuth.mp3"),
    SongAlbumImg: require("../assets/music/TheWayIAm-CharliePuth.jpg"),
    SongLyric: "assets/music/TheWayIAm-CharliePuth.lrc",
    FileSize: "2.84 MB"
  },
  {
    ID: "53",
    UUID: "679babf2-a730-43e0-834a-dbadf39c4f93",
    RawFileName: "Union J - Carry You",
    SongName: "Union J",
    Artist: "Carry You",
    SongUri: require("../assets/music/UnionJ-CarryYou.mp3"),
    SongAlbumImg: null,
    SongLyric: null,
    FileSize: "7.36 MB"
  },
  {
    ID: "54",
    UUID: "54e2906d-a26c-4aec-ac5d-09477f7fcfd2",
    RawFileName: "Viva La Vida - Coldplay",
    SongName: "Viva La Vida",
    Artist: "Coldplay",
    SongUri: require("../assets/music/VivaLaVida-Coldplay.mp3"),
    SongAlbumImg: require("../assets/music/VivaLaVida-Coldplay.jpg"),
    SongLyric: "assets/music/VivaLaVida-Coldplay.lrc",
    FileSize: "9.25 MB"
  },
  {
    ID: "55",
    UUID: "903f022d-afa5-464c-a437-91dbd0410591",
    RawFileName: "Waiting For Love - Avicii,Martin Garrix,Simon Aldred",
    SongName: "Waiting For Love",
    Artist: "Avicii,Martin Garrix,Simon Aldred",
    SongUri: require("../assets/music/WaitingForLove-AviciiANDMartinGarrixANDSimonAldred.mp3"),
    SongAlbumImg: require("../assets/music/WaitingForLove-AviciiANDMartinGarrixANDSimonAldred.jpg"),
    SongLyric: "assets/music/WaitingForLove-AviciiANDMartinGarrixANDSimonAldred.lrc",
    FileSize: "5.28 MB"
  },
  {
    ID: "56",
    UUID: "9486645b-ddfb-40c4-91c1-00d5e25f76ef",
    RawFileName: "Waiting for You - Daniel Padim",
    SongName: "Waiting for You",
    Artist: "Daniel Padim",
    SongUri: require("../assets/music/WaitingforYou-DanielPadim.mp3"),
    SongAlbumImg: require("../assets/music/WaitingforYou-DanielPadim.jpg"),
    SongLyric: null,
    FileSize: "2.75 MB"
  },
  {
    ID: "57",
    UUID: "3dea685b-0f18-49d5-8c1b-f4a08d248a9e",
    RawFileName: "We All Want the Same Thing - Push Baby",
    SongName: "We All Want the Same Thing",
    Artist: "Push Baby",
    SongUri: require("../assets/music/WeAllWanttheSameThing-PushBaby.mp3"),
    SongAlbumImg: require("../assets/music/WeAllWanttheSameThing-PushBaby.jpg"),
    SongLyric: "assets/music/WeAllWanttheSameThing-PushBaby.lrc",
    FileSize: "3.41 MB"
  },
  {
    ID: "58",
    UUID: "a10d961e-896f-4ccb-ad41-69d1ec4249bf",
    RawFileName: "We Don’t Talk Anymore - Charlie Puth,Selena Gomez",
    SongName: "We Don’t Talk Anymore",
    Artist: "Charlie Puth,Selena Gomez",
    SongUri: require("../assets/music/WeDon’tTalkAnymore-CharliePuthANDSelenaGomez.mp3"),
    SongAlbumImg: require("../assets/music/WeDon’tTalkAnymore-CharliePuthANDSelenaGomez.jpg"),
    SongLyric: "assets/music/WeDon’tTalkAnymore-CharliePuthANDSelenaGomez.lrc",
    FileSize: "3.32 MB"
  },
  {
    ID: "59",
    UUID: "5960f364-53a5-435e-a08d-c04888f65bd2",
    RawFileName: "WeAllWanttheSameThing-PushBaby",
    SongName: "WeAllWanttheSameThing",
    Artist: "PushBaby",
    SongUri: require("../assets/music/WeAllWanttheSameThing-PushBaby.mp3"),
    SongAlbumImg: require("../assets/music/WeAllWanttheSameThing-PushBaby.jpg"),
    SongLyric: "assets/music/WeAllWanttheSameThing-PushBaby.lrc",
    FileSize: "3.41 MB"
  },
  {
    ID: "60",
    UUID: "fca86f13-c629-489b-a1e4-4b40257b83e5",
    RawFileName: "What Makes You Beautiful - One Direction",
    SongName: "What Makes You Beautiful",
    Artist: "One Direction",
    SongUri: require("../assets/music/WhatMakesYouBeautiful-OneDirection.mp3"),
    SongAlbumImg: require("../assets/music/WhatMakesYouBeautiful-OneDirection.jpg"),
    SongLyric: "assets/music/WhatMakesYouBeautiful-OneDirection.lrc",
    FileSize: "7.58 MB"
  },
  {
    ID: "61",
    UUID: "70a7043b-ee4a-4d53-a7b5-6cac49e476f5",
    RawFileName: "Your Love - Cash Cash",
    SongName: "Your Love",
    Artist: "Cash Cash",
    SongUri: require("../assets/music/YourLove-CashCash.mp3"),
    SongAlbumImg: null,
    SongLyric: null,
    FileSize: "2.68 MB"
  }
];
export { Songs };
